title: 温故而知新，触类而旁通
name: EbenZhang
markdown: kramdown

github: https://github.com/EbenZhang
weibo: http://weibo.com/fingerpro
twitter: https://twitter.com/EbenZhang
facebook: https://www.facebook.com/EbenZhang

#语法高亮
highlighter: pygments
pygments: true

#首先概要显示分隔符
excerpt_separator: "\n\n\n"

#分页
paginate: 5

#url格式
#permalink: /:year/:month/:day/:title
permalink:  /posts/:title

# comment
comments:
    duoshuo:
        name:  ebenzhanggithubio                             # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
