auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
title: ebenzhang.github.io
url: http://ebenzhang.github.io
baseurl: http://ebenzhang.github.io
feed: /atom.xml
author_info: <a href="http://github.com/ebenzhang">EbenZhang</a>