# Site settings
title: liuyiyou
email: 137515110@qq.com
description: "liuyiyou.cn的个人小站"
baseurl: ""
url: "http//:liuyiyou.cn"
github_username:  liuyiyou

# Build settings
safe: false
#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: [tables]
#pygments: true
hightlighter: true
permalink: pretty
encoding: utf-8
excerpt_separator: "\n\n\n"
paginate: 5
