# Site settings
title: Home
email: 137515110@qq.com
description: "liuyiyou.cn的个人小站"
baseurl: ""
url: "http//:liuyiyou.cn"
github_username:  liuyiyou

# Build settings
markdown: kramdown
permalink: pretty
Encoding: UTF-8
excerpt_separator: "\n\n\n"
