title: 温故而知新，触类而旁通
name: liuyiyou
markdown: kramdown

github: https://github.com/liuyiyou
weibo: http://weibo.com/virgots
twitter: https://twitter.com/liuyiyoucool
facebook: https://www.facebook.com/liu.yiyou.35

#语法高亮
pygments: true

#首先概要显示分隔符
excerpt_separator: "\n\n\n"

markdown: kramdown

#分页
paginate: 10

#url格式
#permalink: /:year/:month/:day/:title
permalink:  /posts/:title

# comment
comments:
    duoshuo:
        name:  liuyiyou                             # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26